### PR TITLE
feat: add no_std ccsds packets

### PR DESCRIPTION
**Pull request by amsmith-pro**

### CODE REVIEW

**Comment by amsmith-pro** [comment]
@owlot @GoodluckH Can I remove the LICENSE from this one? Seems really helpful for lots of aerospace applications, doesn't really need to be behind a license

**Comment by GoodluckH** [comment]
What are we trying to build for this lib? Can't we use existing crates like https://crates.io/crates/ccsds_spacepacket

**Comment by amsmith-pro** [comment]
> What are we trying to build for this lib? Can't we use existing crates like https://crates.io/crates/ccsds_spacepacket

Main reasons against ccsds_spacepacket:
- No `no_std` (heapless) support, not compatible with many embedded contexts
- Insufficient docs
- Limited Features
- Only a couple UTs
- Hasn't been updated in over a year
    - Open issue from Aug 2021 to add docs that's still open
- Few active users to provide feedback

Another option is https://github.com/us-irs/spacepackets-rs, which does have `no_std` support. However, their documentation is also limited and I'm not a huge fan of their naming schemes or packet construction method.

This is a dep we're going to use a lot, would prefer to have direct access to add or change features where we don't need to depend on a third party

**Comment by GoodluckH** [comment]
Great. I'm ok with making this a MIT license or similar. It benefits the whole community.

**Review by GoodluckH — APPROVED** [review]

**Pull request merged**
